// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for ChannelChannelType.
const (
	ChannelChannelTypeText  ChannelChannelType = "text"
	ChannelChannelTypeVoice ChannelChannelType = "voice"
)

// Defines values for ChannelToCreateChannelType.
const (
	ChannelToCreateChannelTypeText  ChannelToCreateChannelType = "text"
	ChannelToCreateChannelTypeVoice ChannelToCreateChannelType = "voice"
)

// AdminUserToUpdate defines model for AdminUserToUpdate.
type AdminUserToUpdate struct {
	Confirmed bool `json:"confirmed"`
}

// AdminUsersPage defines model for AdminUsersPage.
type AdminUsersPage struct {
	Items      []User  `json:"items"`
	NextCursor *string `json:"next_cursor,omitempty"`
}

// Channel defines model for Channel.
type Channel struct {
	AuthorId    string             `json:"author_id"`
	ChannelType ChannelChannelType `json:"channel_type"`
	CreatedAt   time.Time          `json:"created_at"`
	Id          string             `json:"id"`
	Name        string             `json:"name"`
	SpaceId     string             `json:"space_id"`
	UpdatedAt   *time.Time         `json:"updated_at,omitempty"`
}

// ChannelChannelType defines model for Channel.ChannelType.
type ChannelChannelType string

// ChannelMessage defines model for ChannelMessage.
type ChannelMessage struct {
	Author    ChannelMessageAuthor `json:"author"`
	AuthorId  string               `json:"author_id"`
	Body      string               `json:"body"`
	ChannelId string               `json:"channel_id"`
	CreatedAt time.Time            `json:"created_at"`
	Id        string               `json:"id"`
}

// ChannelMessageAuthor defines model for ChannelMessageAuthor.
type ChannelMessageAuthor struct {
	Id       string `json:"id"`
	IsAdmin  bool   `json:"is_admin"`
	Username string `json:"username"`
}

// ChannelMessageToCreate defines model for ChannelMessageToCreate.
type ChannelMessageToCreate struct {
	Body string `json:"body"`
}

// ChannelMessagesPage defines model for ChannelMessagesPage.
type ChannelMessagesPage struct {
	Items      []ChannelMessage `json:"items"`
	NextCursor *string          `json:"next_cursor,omitempty"`
}

// ChannelToCreate defines model for ChannelToCreate.
type ChannelToCreate struct {
	ChannelType ChannelToCreateChannelType `json:"channel_type"`
	Name        string                     `json:"name"`
	SpaceId     string                     `json:"space_id"`
}

// ChannelToCreateChannelType defines model for ChannelToCreate.ChannelType.
type ChannelToCreateChannelType string

// ChannelToUpdate defines model for ChannelToUpdate.
type ChannelToUpdate struct {
	Name string `json:"name"`
}

// ErrorMap defines model for ErrorMap.
type ErrorMap map[string]string

// IdResponse defines model for IdResponse.
type IdResponse struct {
	Id string `json:"id"`
}

// MeToUpdate defines model for MeToUpdate.
type MeToUpdate struct {
	Username string `json:"username"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// Space defines model for Space.
type Space struct {
	AuthorId  string     `json:"author_id"`
	CreatedAt time.Time  `json:"created_at"`
	Id        string     `json:"id"`
	Name      string     `json:"name"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// SpaceMemberToCreate defines model for SpaceMemberToCreate.
type SpaceMemberToCreate struct {
	SpaceId string `json:"space_id"`
	UserId  string `json:"user_id"`
}

// SpaceMemberView defines model for SpaceMemberView.
type SpaceMemberView struct {
	AvatarUrl     *string              `json:"avatar_url"`
	CreatedAt     time.Time            `json:"created_at"`
	Email         *openapi_types.Email `json:"email,omitempty"`
	IsAdmin       bool                 `json:"is_admin"`
	SpaceId       string               `json:"space_id"`
	SpaceMemberId string               `json:"space_member_id"`
	UserId        string               `json:"user_id"`
	Username      string               `json:"username"`
}

// SpaceToCreate defines model for SpaceToCreate.
type SpaceToCreate struct {
	Name string `json:"name"`
}

// SpaceToUpdate defines model for SpaceToUpdate.
type SpaceToUpdate struct {
	Name string `json:"name"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse map[string]string

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken  *string `json:"access_token,omitempty"`
	ExpiresIn    *int64  `json:"expires_in,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
	TokenType    *string `json:"token_type,omitempty"`
	User         *User   `json:"user,omitempty"`
}

// User defines model for User.
type User struct {
	Confirmed   *bool                `json:"confirmed,omitempty"`
	ConfirmedAt *time.Time           `json:"confirmed_at,omitempty"`
	ConfirmedBy *string              `json:"confirmed_by"`
	CreatedAt   *time.Time           `json:"created_at,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	Id          *string              `json:"id,omitempty"`
	IsAdmin     *bool                `json:"is_admin,omitempty"`
	Username    *string              `json:"username,omitempty"`
}

// UserSearchPage defines model for UserSearchPage.
type UserSearchPage struct {
	Items      []UserSearchResult `json:"items"`
	NextCursor *string            `json:"next_cursor,omitempty"`
}

// UserSearchResult defines model for UserSearchResult.
type UserSearchResult struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	Id       string               `json:"id"`
	IsAdmin  bool                 `json:"is_admin"`
	Username string               `json:"username"`
}

// VoiceMember defines model for VoiceMember.
type VoiceMember struct {
	AvatarUrl *string `json:"avatar_url"`
	Deafened  bool    `json:"deafened"`
	Id        string  `json:"id"`
	IsAdmin   bool    `json:"is_admin"`
	Muted     bool    `json:"muted"`
	Username  string  `json:"username"`
}

// VoiceStateUpdate defines model for VoiceStateUpdate.
type VoiceStateUpdate struct {
	Deafened bool `json:"deafened"`
	Muted    bool `json:"muted"`
}

// WebRTCBootstrapResponse defines model for WebRTCBootstrapResponse.
type WebRTCBootstrapResponse struct {
	ConnectionId string            `json:"connection_id"`
	Publishers   []WebRTCPublisher `json:"publishers"`
	RoomId       string            `json:"room_id"`
	SelfFeedId   string            `json:"self_feed_id"`
}

// WebRTCPublisher defines model for WebRTCPublisher.
type WebRTCPublisher struct {
	Display *string `json:"display"`
	FeedId  string  `json:"feed_id"`
}

// ListAdminUsersParams defines parameters for ListAdminUsers.
type ListAdminUsersParams struct {
	Query     *string `form:"query,omitempty" json:"query,omitempty"`
	Limit     *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor    *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Confirmed *bool   `form:"confirmed,omitempty" json:"confirmed,omitempty"`
}

// GithubCallbackParams defines parameters for GithubCallback.
type GithubCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// GoogleCallbackParams defines parameters for GoogleCallback.
type GoogleCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// YandexCallbackParams defines parameters for YandexCallback.
type YandexCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// ListChannelMessagesParams defines parameters for ListChannelMessages.
type ListChannelMessagesParams struct {
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// SearchUsersParams defines parameters for SearchUsers.
type SearchUsersParams struct {
	Query  *string `form:"query,omitempty" json:"query,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// UpdateAdminUserJSONRequestBody defines body for UpdateAdminUser for application/json ContentType.
type UpdateAdminUserJSONRequestBody = AdminUserToUpdate

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// CreateChannelJSONRequestBody defines body for CreateChannel for application/json ContentType.
type CreateChannelJSONRequestBody = ChannelToCreate

// UpdateChannelJSONRequestBody defines body for UpdateChannel for application/json ContentType.
type UpdateChannelJSONRequestBody = ChannelToUpdate

// CreateChannelMessageJSONRequestBody defines body for CreateChannelMessage for application/json ContentType.
type CreateChannelMessageJSONRequestBody = ChannelMessageToCreate

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = MeToUpdate

// CreateSpaceMemberJSONRequestBody defines body for CreateSpaceMember for application/json ContentType.
type CreateSpaceMemberJSONRequestBody = SpaceMemberToCreate

// CreateSpaceJSONRequestBody defines body for CreateSpace for application/json ContentType.
type CreateSpaceJSONRequestBody = SpaceToCreate

// UpdateSpaceJSONRequestBody defines body for UpdateSpace for application/json ContentType.
type UpdateSpaceJSONRequestBody = SpaceToUpdate

// UpdateVoiceStateJSONRequestBody defines body for UpdateVoiceState for application/json ContentType.
type UpdateVoiceStateJSONRequestBody = VoiceStateUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// list users (admin only)
	// (GET /api/admin/users)
	ListAdminUsers(c *fiber.Ctx, params ListAdminUsersParams) error
	// update user (admin only)
	// (PATCH /api/admin/users/{id})
	UpdateAdminUser(c *fiber.Ctx, id string) error
	// start github oauth
	// (GET /api/auth/github)
	GithubLogin(c *fiber.Ctx) error
	// github oauth callback
	// (GET /api/auth/github/callback)
	GithubCallback(c *fiber.Ctx, params GithubCallbackParams) error
	// start google oauth
	// (GET /api/auth/google)
	GoogleLogin(c *fiber.Ctx) error
	// google oauth callback
	// (GET /api/auth/google/callback)
	GoogleCallback(c *fiber.Ctx, params GoogleCallbackParams) error
	// health check
	// (GET /api/auth/health)
	Health(c *fiber.Ctx) error
	// logout
	// (POST /api/auth/logout)
	Logout(c *fiber.Ctx) error
	// refresh tokens
	// (POST /api/auth/refresh)
	Refresh(c *fiber.Ctx) error
	// start yandex oauth
	// (GET /api/auth/yandex)
	YandexLogin(c *fiber.Ctx) error
	// yandex oauth callback
	// (GET /api/auth/yandex/callback)
	YandexCallback(c *fiber.Ctx, params YandexCallbackParams) error
	// create channel
	// (POST /api/channels)
	CreateChannel(c *fiber.Ctx) error
	// bootstrap janus webrtc signaling for voice channel
	// (POST /api/channels/voice/{id}/webrtc/bootstrap)
	VoiceWebRTCBootstrap(c *fiber.Ctx, id string) error
	// delete channel
	// (DELETE /api/channels/{id})
	DeleteChannel(c *fiber.Ctx, id string) error
	// get channel by id
	// (GET /api/channels/{id})
	GetChannelByID(c *fiber.Ctx, id string) error
	// update channel
	// (PATCH /api/channels/{id})
	UpdateChannel(c *fiber.Ctx, id string) error
	// list channel chat messages
	// (GET /api/channels/{id}/messages)
	ListChannelMessages(c *fiber.Ctx, id string, params ListChannelMessagesParams) error
	// create channel chat message
	// (POST /api/channels/{id}/messages)
	CreateChannelMessage(c *fiber.Ctx, id string) error
	// get current user
	// (GET /api/me)
	GetMe(c *fiber.Ctx) error
	// update current user
	// (PATCH /api/me)
	UpdateMe(c *fiber.Ctx) error
	// create space member
	// (POST /api/space-members)
	CreateSpaceMember(c *fiber.Ctx) error
	// delete space member
	// (DELETE /api/space-members/{id})
	DeleteSpaceMember(c *fiber.Ctx, id string) error
	// list spaces
	// (GET /api/spaces)
	ListSpaces(c *fiber.Ctx) error
	// create space
	// (POST /api/spaces)
	CreateSpace(c *fiber.Ctx) error
	// get space by id
	// (GET /api/spaces/{id})
	GetSpaceByID(c *fiber.Ctx, id string) error
	// delete space
	// (DELETE /api/spaces/{id}/channels)
	DeleteSpace(c *fiber.Ctx, id string) error
	// list channels by space id
	// (GET /api/spaces/{id}/channels)
	ListChannelsBySpace(c *fiber.Ctx, id string) error
	// update space
	// (PATCH /api/spaces/{id}/channels)
	UpdateSpace(c *fiber.Ctx, id string) error
	// list space members (owner only)
	// (GET /api/spaces/{id}/members)
	ListSpaceMembers(c *fiber.Ctx, id string) error
	// remove user from space (owner only)
	// (DELETE /api/spaces/{spaceId}/members/{userId})
	RemoveSpaceMember(c *fiber.Ctx, spaceId string, userId string) error
	// search confirmed users
	// (GET /api/users/search)
	SearchUsers(c *fiber.Ctx, params SearchUsersParams) error
	// join voice channel (presence)
	// (POST /api/voice/channels/{id}/join)
	JoinVoiceChannel(c *fiber.Ctx, id string) error
	// list voice members (presence)
	// (GET /api/voice/channels/{id}/members)
	ListVoiceMembers(c *fiber.Ctx, id string) error
	// voice presence heartbeat
	// (POST /api/voice/heartbeat)
	VoiceHeartbeat(c *fiber.Ctx) error
	// leave active voice channel (presence)
	// (POST /api/voice/leave)
	LeaveVoice(c *fiber.Ctx) error
	// update voice state (muted/deafened)
	// (POST /api/voice/state)
	UpdateVoiceState(c *fiber.Ctx) error
	// user scoped events websocket
	// (GET /api/ws/events)
	EventsWebSocket(c *fiber.Ctx) error
	// webrtc signaling websocket
	// (GET /api/ws/webrtc/{connectionId})
	WebRTCWebSocket(c *fiber.Ctx, connectionId string) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// ListAdminUsers operation middleware
func (siw *ServerInterfaceWrapper) ListAdminUsers(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAdminUsersParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, false, "query", query, &params.Query)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter query: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", query, &params.Cursor)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cursor: %w", err).Error())
	}

	// ------------- Optional query parameter "confirmed" -------------

	err = runtime.BindQueryParameter("form", true, false, "confirmed", query, &params.Confirmed)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter confirmed: %w", err).Error())
	}

	return siw.Handler.ListAdminUsers(c, params)
}

// UpdateAdminUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateAdminUser(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.UpdateAdminUser(c, id)
}

// GithubLogin operation middleware
func (siw *ServerInterfaceWrapper) GithubLogin(c *fiber.Ctx) error {

	return siw.Handler.GithubLogin(c)
}

// GithubCallback operation middleware
func (siw *ServerInterfaceWrapper) GithubCallback(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GithubCallbackParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "code" -------------

	if paramValue := c.Query("code"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument code is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "code", query, &params.Code)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter code: %w", err).Error())
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := c.Query("state"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument state is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "state", query, &params.State)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter state: %w", err).Error())
	}

	return siw.Handler.GithubCallback(c, params)
}

// GoogleLogin operation middleware
func (siw *ServerInterfaceWrapper) GoogleLogin(c *fiber.Ctx) error {

	return siw.Handler.GoogleLogin(c)
}

// GoogleCallback operation middleware
func (siw *ServerInterfaceWrapper) GoogleCallback(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GoogleCallbackParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "code" -------------

	if paramValue := c.Query("code"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument code is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "code", query, &params.Code)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter code: %w", err).Error())
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := c.Query("state"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument state is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "state", query, &params.State)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter state: %w", err).Error())
	}

	return siw.Handler.GoogleCallback(c, params)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.Health(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *fiber.Ctx) error {

	return siw.Handler.Logout(c)
}

// Refresh operation middleware
func (siw *ServerInterfaceWrapper) Refresh(c *fiber.Ctx) error {

	return siw.Handler.Refresh(c)
}

// YandexLogin operation middleware
func (siw *ServerInterfaceWrapper) YandexLogin(c *fiber.Ctx) error {

	return siw.Handler.YandexLogin(c)
}

// YandexCallback operation middleware
func (siw *ServerInterfaceWrapper) YandexCallback(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params YandexCallbackParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "code" -------------

	if paramValue := c.Query("code"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument code is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "code", query, &params.Code)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter code: %w", err).Error())
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := c.Query("state"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument state is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "state", query, &params.State)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter state: %w", err).Error())
	}

	return siw.Handler.YandexCallback(c, params)
}

// CreateChannel operation middleware
func (siw *ServerInterfaceWrapper) CreateChannel(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.CreateChannel(c)
}

// VoiceWebRTCBootstrap operation middleware
func (siw *ServerInterfaceWrapper) VoiceWebRTCBootstrap(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.VoiceWebRTCBootstrap(c, id)
}

// DeleteChannel operation middleware
func (siw *ServerInterfaceWrapper) DeleteChannel(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.DeleteChannel(c, id)
}

// GetChannelByID operation middleware
func (siw *ServerInterfaceWrapper) GetChannelByID(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.GetChannelByID(c, id)
}

// UpdateChannel operation middleware
func (siw *ServerInterfaceWrapper) UpdateChannel(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.UpdateChannel(c, id)
}

// ListChannelMessages operation middleware
func (siw *ServerInterfaceWrapper) ListChannelMessages(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListChannelMessagesParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", query, &params.Cursor)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cursor: %w", err).Error())
	}

	return siw.Handler.ListChannelMessages(c, id, params)
}

// CreateChannelMessage operation middleware
func (siw *ServerInterfaceWrapper) CreateChannelMessage(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.CreateChannelMessage(c, id)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.GetMe(c)
}

// UpdateMe operation middleware
func (siw *ServerInterfaceWrapper) UpdateMe(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.UpdateMe(c)
}

// CreateSpaceMember operation middleware
func (siw *ServerInterfaceWrapper) CreateSpaceMember(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.CreateSpaceMember(c)
}

// DeleteSpaceMember operation middleware
func (siw *ServerInterfaceWrapper) DeleteSpaceMember(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.DeleteSpaceMember(c, id)
}

// ListSpaces operation middleware
func (siw *ServerInterfaceWrapper) ListSpaces(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.ListSpaces(c)
}

// CreateSpace operation middleware
func (siw *ServerInterfaceWrapper) CreateSpace(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.CreateSpace(c)
}

// GetSpaceByID operation middleware
func (siw *ServerInterfaceWrapper) GetSpaceByID(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.GetSpaceByID(c, id)
}

// DeleteSpace operation middleware
func (siw *ServerInterfaceWrapper) DeleteSpace(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.DeleteSpace(c, id)
}

// ListChannelsBySpace operation middleware
func (siw *ServerInterfaceWrapper) ListChannelsBySpace(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.ListChannelsBySpace(c, id)
}

// UpdateSpace operation middleware
func (siw *ServerInterfaceWrapper) UpdateSpace(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.UpdateSpace(c, id)
}

// ListSpaceMembers operation middleware
func (siw *ServerInterfaceWrapper) ListSpaceMembers(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.ListSpaceMembers(c, id)
}

// RemoveSpaceMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveSpaceMember(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "spaceId" -------------
	var spaceId string

	err = runtime.BindStyledParameterWithOptions("simple", "spaceId", c.Params("spaceId"), &spaceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter spaceId: %w", err).Error())
	}

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Params("userId"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.RemoveSpaceMember(c, spaceId, userId)
}

// SearchUsers operation middleware
func (siw *ServerInterfaceWrapper) SearchUsers(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchUsersParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, false, "query", query, &params.Query)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter query: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", query, &params.Cursor)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cursor: %w", err).Error())
	}

	return siw.Handler.SearchUsers(c, params)
}

// JoinVoiceChannel operation middleware
func (siw *ServerInterfaceWrapper) JoinVoiceChannel(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.JoinVoiceChannel(c, id)
}

// ListVoiceMembers operation middleware
func (siw *ServerInterfaceWrapper) ListVoiceMembers(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.ListVoiceMembers(c, id)
}

// VoiceHeartbeat operation middleware
func (siw *ServerInterfaceWrapper) VoiceHeartbeat(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.VoiceHeartbeat(c)
}

// LeaveVoice operation middleware
func (siw *ServerInterfaceWrapper) LeaveVoice(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.LeaveVoice(c)
}

// UpdateVoiceState operation middleware
func (siw *ServerInterfaceWrapper) UpdateVoiceState(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.UpdateVoiceState(c)
}

// EventsWebSocket operation middleware
func (siw *ServerInterfaceWrapper) EventsWebSocket(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.EventsWebSocket(c)
}

// WebRTCWebSocket operation middleware
func (siw *ServerInterfaceWrapper) WebRTCWebSocket(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "connectionId" -------------
	var connectionId string

	err = runtime.BindStyledParameterWithOptions("simple", "connectionId", c.Params("connectionId"), &connectionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter connectionId: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.WebRTCWebSocket(c, connectionId)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/api/admin/users", wrapper.ListAdminUsers)

	router.Patch(options.BaseURL+"/api/admin/users/:id", wrapper.UpdateAdminUser)

	router.Get(options.BaseURL+"/api/auth/github", wrapper.GithubLogin)

	router.Get(options.BaseURL+"/api/auth/github/callback", wrapper.GithubCallback)

	router.Get(options.BaseURL+"/api/auth/google", wrapper.GoogleLogin)

	router.Get(options.BaseURL+"/api/auth/google/callback", wrapper.GoogleCallback)

	router.Get(options.BaseURL+"/api/auth/health", wrapper.Health)

	router.Post(options.BaseURL+"/api/auth/logout", wrapper.Logout)

	router.Post(options.BaseURL+"/api/auth/refresh", wrapper.Refresh)

	router.Get(options.BaseURL+"/api/auth/yandex", wrapper.YandexLogin)

	router.Get(options.BaseURL+"/api/auth/yandex/callback", wrapper.YandexCallback)

	router.Post(options.BaseURL+"/api/channels", wrapper.CreateChannel)

	router.Post(options.BaseURL+"/api/channels/voice/:id/webrtc/bootstrap", wrapper.VoiceWebRTCBootstrap)

	router.Delete(options.BaseURL+"/api/channels/:id", wrapper.DeleteChannel)

	router.Get(options.BaseURL+"/api/channels/:id", wrapper.GetChannelByID)

	router.Patch(options.BaseURL+"/api/channels/:id", wrapper.UpdateChannel)

	router.Get(options.BaseURL+"/api/channels/:id/messages", wrapper.ListChannelMessages)

	router.Post(options.BaseURL+"/api/channels/:id/messages", wrapper.CreateChannelMessage)

	router.Get(options.BaseURL+"/api/me", wrapper.GetMe)

	router.Patch(options.BaseURL+"/api/me", wrapper.UpdateMe)

	router.Post(options.BaseURL+"/api/space-members", wrapper.CreateSpaceMember)

	router.Delete(options.BaseURL+"/api/space-members/:id", wrapper.DeleteSpaceMember)

	router.Get(options.BaseURL+"/api/spaces", wrapper.ListSpaces)

	router.Post(options.BaseURL+"/api/spaces", wrapper.CreateSpace)

	router.Get(options.BaseURL+"/api/spaces/:id", wrapper.GetSpaceByID)

	router.Delete(options.BaseURL+"/api/spaces/:id/channels", wrapper.DeleteSpace)

	router.Get(options.BaseURL+"/api/spaces/:id/channels", wrapper.ListChannelsBySpace)

	router.Patch(options.BaseURL+"/api/spaces/:id/channels", wrapper.UpdateSpace)

	router.Get(options.BaseURL+"/api/spaces/:id/members", wrapper.ListSpaceMembers)

	router.Delete(options.BaseURL+"/api/spaces/:spaceId/members/:userId", wrapper.RemoveSpaceMember)

	router.Get(options.BaseURL+"/api/users/search", wrapper.SearchUsers)

	router.Post(options.BaseURL+"/api/voice/channels/:id/join", wrapper.JoinVoiceChannel)

	router.Get(options.BaseURL+"/api/voice/channels/:id/members", wrapper.ListVoiceMembers)

	router.Post(options.BaseURL+"/api/voice/heartbeat", wrapper.VoiceHeartbeat)

	router.Post(options.BaseURL+"/api/voice/leave", wrapper.LeaveVoice)

	router.Post(options.BaseURL+"/api/voice/state", wrapper.UpdateVoiceState)

	router.Get(options.BaseURL+"/api/ws/events", wrapper.EventsWebSocket)

	router.Get(options.BaseURL+"/api/ws/webrtc/:connectionId", wrapper.WebRTCWebSocket)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdW3PUOBb+KyrvPjBVPXFYmN2qfgsZBjJDGCoJTO0yqYzaPt0WsSUjyUl6UvnvW5J8",
	"v7Vt2k0a/ASJdTmX71ykIyn3lsOCkFGgUljze0s4HgRY//fIDQh9L4BfsPehiyWoX2LXJZIwiv13nIXA",
	"JQFhzZfYFzCzwtyv1MB0SXgArvpBrkOw5taCMR8wtR4eZhaHzxHh6vPHXNvLWdKWLT6BI62HWUaJeIdX",
	"fckgEoLif/7JYWnNrX/YGet2zLetZlFTxjRgzvFa/UzhTl45EReM59gRkhO6qnBjZqrj5NjDlILfkwUc",
	"SY/xK+LWTD2zHDPmlflwbwGNAkWFhDtpzawbRhzIEZPryAFLcK+wVN2WjAfqf5ZS9Y+SBGDV9GmggeIA",
	"aj+IEDvQRHmkYdWHgLKgXWuWk05uupikknQKPLfo5xSE6I80Q8gmhBWnODJ9HmYblLxg7rpV+03g2JaO",
	"6ySfm7uoBk1tYfLkewepH6Vi7GPl9ewTcYWV86hzQTMrEsAbkFvHbto8N+5mdi7YsRZDT4YaFF6iS7fa",
	"TMP4frNkOKN70IFSHewrhzi4Ek8bfFMrs4MCcDdo61Z1k7/knPFTHDbPWiOOyign7hmIkFGhSelgtFXL",
	"qyPuFAYKpbvNpy3r5j+DJQfhncHnCISsssbN9yvJroHWz1UZ81wBZLupwQ4i/PaDeGId7aFaS+sUgoVK",
	"UAc5g/bcRADva9ZJnw3kfiBw21fNN1hifhVxnTrSyPfxwgdrLnkEW8rsIMDELzQ3v5n1jaqtYjUfAy2H",
	"/qLvE7LLM83qNFUf1LthbyDqvtArx1N/jYBwLrGMRN6dDw8LF8ovNkcG7DggRKP3nFlwFxIO4sqAMIUs",
	"ofLfzzPIEiphZRZ0mxzyzNJf0sygFnndVo91/L6Pe29r/TzLPvey8qzXYv0oXMn28/Za2Z8D5o63k+0D",
	"M9UZiMiXIybClan68fV1dTR4bfVBZegmjI4bQl3AS6BNxjdIJEEkm8bbgrSS8XOkNwpQeXIYFELaxdLI",
	"YYmJTpT+AYuzi+MXjEkhOQ43x50mL0rBUY2bUoowWvhEeMC7m7kh7V3Ssc7KOWNBYxIE/vJqCeB2SjCL",
	"HGQjl8YpMNIsz4zonoonIvRxt5jRmbWkYZVcLSUn4kSuz5XQDRFHIfkN1keR9LSqqDW3PMAu8GTVMLfM",
	"7hH5Gyu+Mm+GdU/rQQ1M6JIZLAuHk1A3nFv/A07+Bg+jBXaugbro6N2J6k+k4jT7bH59A1yYfk8PDhXP",
	"LASKQ2LNrWcHhwfPlDqw9DTVNg6JrY3UVoarf7cC7bCVhDWlJ641t94QIbO9bj0ExwFI3edjzPDnCPg6",
	"4zf50UCzVuT1HX0SEFnoGOA7EkSBNf/pcGYFhJofnlazqaYh46A2gJgs16npnHmRSwUf4wa0FP91eBjb",
	"uARqImAY+sTRIrU/CUazmsYmmy4VGTRSigj5/Tel6OeHT7c2Z7rFUjPbe4pjKINr5n22k3l/YXxBXBe0",
	"Q/9piwJum/SEShXRfHQO/AY40m0LXkAbQN7+P14qOIgoCDBfazwLibR9oSfa2BCj/voHZcJ4pezHlJGs",
	"SzVq2STte+I+6GUIlo5XtUwTK1OINJimsvgM08ZZp97O+Mpmy7g0jUHIF/HW73Zhna4ZH4peWNH1ULGr",
	"51UH+Zah45giDcfdIOMFdlGyy/a9Wd9zo4bRJ33LJPqFRdTdM5M3W4/a6DvbfCQ9e0WkFy1yYbhIGQeX",
	"cHCkQJKhV0S+jhbod03BrOQWXumB3rCVzr8LJvTs8D/VkS8gCBnHfI3O4jkMwylHQmIukaEPMWzmTHlR",
	"P9ayYjvY91Xe0sgT3DkepisQyGEuzBAHGXGqOLwGKhoYO05G7ZSJqIF7ebyGXECoxUl/1zlSWlDcqGrJ",
	"Cr6KO3wExppiN49a5GTQaYUvYysfOlqibttkifrj9i3RzNnJEnXT7VuiHnayxMkSe1hiDrVdLdED7Jtl",
	"dS1qzWfkeKBHKmL0tek7ou5LpYcG5ffJHUoMtYnGZysWmRovEzWycXzAXCAjbcauCVTN+I0Zo2+eXVCr",
	"n4zRRmxc52imNvM/cVPjedCScUThNv4pxIRXmIiL3tY4K5VSSb3TMuV78S5fa9nzmLxaAa5igxmsMXXh",
	"rlti8V/dtiGxMB+3nlgY+jolFqbp1hMLw9iUWEyJRXcTzKO2Q2IRn28T+WBUBKE5QZGcih4nrpRPDO44",
	"sOQOwE3QGrzVY44hICdFSgK54wRjVdjZ+jin3tq1b2HBpWMvkmpiMyR1gbRUexxtv3ckzDWVTqe0ZtrN",
	"fbQmntom+oRpJJAxWSTIimKf0JVeoWiTrnEDH8zJ7aoPSAo7LvhgTjsUzf1n/fssAu3AzjvUViaktCHF",
	"6LI9GMzqS+yvQMaNXqxPft43v57AtMWPT8hpQ84KZAIbtFgjrdpa8LTWgcf2FiPmwN9GDXgCeYeyaL9c",
	"WWfJQXxdrPWEUulq2RhW0P/I0tPD8c4s7cCjF+7pTVn6lKU/7mNWSQh1PCxRkDmC+lC6eecnuTa6dwG1",
	"fMd32luanMbkNDbs3hXcRnt6EkBjKvIK5CmMWXOOL3M9smPA+7bYijgHag7m5lRtDrhvXGidwkg1gdz1",
	"8R277E2o2pV2b7BPXMSnEvOAhVU7phPfpa8b/2guIG8sgeWuh48E+br78lO6sr+lMA0vFCSQSVCo1dwI",
	"w47b4UU0Tlvie7Ml3gsU7ds8cZ8vdAedrlOah08qlyibXMS+rZZFIsmKOmabY8KY0WCKA99KHNhs66nn",
	"b1pM6X77WBSLvcdUEhu+SjNho1wQa0NS4WxXh2RiSiP2Lo2oD1ibykLixXqHCh8hGUlr7F3TkQlT3SsG",
	"QjkZ420G1t7HBddoidZUd/9u6u59EjI7tz3UvhI7jRvuq1stv3/Yw71OhaTJxCrr6XiTQ6An7JYCr1z8",
	"b7Q6/e9JZnr2fSSAn7Rvi51BwG56b4vFUw06+lIcyZA4fnY8mdpkaul1OwV587jGkrMgNruu5mae1RH6",
	"gcLG6GbeL/x2X7u6HLmQmHvVcipUD4e6QSlKHyEzz0i1lPbMxaLi2clPzLz7WL+j+ysjVN9ReGw3DabD",
	"QVOg+brWpwyneK8HPQk5CKAO/NByxafOCLssp3JPyO7vcir/Du60lJrMbuBSyphdupTqbnYeYC4XgOWG",
	"i7Sv03b7sxzZIyUa/SVqQ15O2u368wHfQLPu3qjPpuektzGMT8kXYUeSGxge+8wzGo1KNHvO2YPfIx0l",
	"qLwoPj0w+l0cgzSw1RhET/SL7nbynnsbdG+FDTfJn5usfcjmD1icM+caJLol0tOLsR+Fw0JwUciZGzkS",
	"mREQdjgTAmHfR+YvhpCFH2/Ai4M/6UvVCoV47TPsquWd5NiRiAjkMicKgEpwEaHor/jJb9tljrBffnj5",
	"9uL8IHD/OviTVp7N0WOKlMSye3xq4FNk6PyWSMcjdIXecSaZw3zx3SG8F8AEcBRrPNb0LSxEIvAEWUYV",
	"RWjF73zcZ4/mnxSOvTQhLQpXHLuAgLohI1TqxwZ+1e8QZA8QPGHLJXAbU3EL3JacONe+dtNFiJjXN/IQ",
	"2bzGyNP7RauNCYBbAGDl6Yk6+KWOTY+snKnRrv4LI5ZtPVw+/D8AAP//V0LwDF53AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
