// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for ChannelChannelType.
const (
	ChannelChannelTypeText  ChannelChannelType = "text"
	ChannelChannelTypeVoice ChannelChannelType = "voice"
)

// Defines values for ChannelToCreateChannelType.
const (
	ChannelToCreateChannelTypeText  ChannelToCreateChannelType = "text"
	ChannelToCreateChannelTypeVoice ChannelToCreateChannelType = "voice"
)

// Channel defines model for Channel.
type Channel struct {
	AuthorId    string             `json:"author_id"`
	ChannelType ChannelChannelType `json:"channel_type"`
	CreatedAt   time.Time          `json:"created_at"`
	Id          string             `json:"id"`
	Name        string             `json:"name"`
	SpaceId     string             `json:"space_id"`
	UpdatedAt   *time.Time         `json:"updated_at,omitempty"`
}

// ChannelChannelType defines model for Channel.ChannelType.
type ChannelChannelType string

// ChannelToCreate defines model for ChannelToCreate.
type ChannelToCreate struct {
	ChannelType ChannelToCreateChannelType `json:"channel_type"`
	Name        string                     `json:"name"`
	SpaceId     string                     `json:"space_id"`
}

// ChannelToCreateChannelType defines model for ChannelToCreate.ChannelType.
type ChannelToCreateChannelType string

// ChannelToUpdate defines model for ChannelToUpdate.
type ChannelToUpdate struct {
	Name string `json:"name"`
}

// ErrorMap defines model for ErrorMap.
type ErrorMap map[string]string

// IdResponse defines model for IdResponse.
type IdResponse struct {
	Id string `json:"id"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// Space defines model for Space.
type Space struct {
	AuthorId  string     `json:"author_id"`
	CreatedAt time.Time  `json:"created_at"`
	Id        string     `json:"id"`
	Name      string     `json:"name"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// SpaceMemberToCreate defines model for SpaceMemberToCreate.
type SpaceMemberToCreate struct {
	SpaceId string `json:"space_id"`
	UserId  string `json:"user_id"`
}

// SpaceToCreate defines model for SpaceToCreate.
type SpaceToCreate struct {
	Name string `json:"name"`
}

// SpaceToUpdate defines model for SpaceToUpdate.
type SpaceToUpdate struct {
	Name string `json:"name"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse map[string]string

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken  *string `json:"access_token,omitempty"`
	ExpiresIn    *int64  `json:"expires_in,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
	TokenType    *string `json:"token_type,omitempty"`
	User         *User   `json:"user,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt *time.Time           `json:"created_at,omitempty"`
	Email     *openapi_types.Email `json:"email,omitempty"`
	Id        *string              `json:"id,omitempty"`
	Username  *string              `json:"username,omitempty"`
}

// GithubCallbackParams defines parameters for GithubCallback.
type GithubCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// GoogleCallbackParams defines parameters for GoogleCallback.
type GoogleCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// CreateChannelJSONRequestBody defines body for CreateChannel for application/json ContentType.
type CreateChannelJSONRequestBody = ChannelToCreate

// UpdateChannelJSONRequestBody defines body for UpdateChannel for application/json ContentType.
type UpdateChannelJSONRequestBody = ChannelToUpdate

// CreateSpaceMemberJSONRequestBody defines body for CreateSpaceMember for application/json ContentType.
type CreateSpaceMemberJSONRequestBody = SpaceMemberToCreate

// CreateSpaceJSONRequestBody defines body for CreateSpace for application/json ContentType.
type CreateSpaceJSONRequestBody = SpaceToCreate

// UpdateSpaceJSONRequestBody defines body for UpdateSpace for application/json ContentType.
type UpdateSpaceJSONRequestBody = SpaceToUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// start github oauth
	// (GET /api/auth/github)
	GithubLogin(c *fiber.Ctx) error
	// github oauth callback
	// (GET /api/auth/github/callback)
	GithubCallback(c *fiber.Ctx, params GithubCallbackParams) error
	// start google oauth
	// (GET /api/auth/google)
	GoogleLogin(c *fiber.Ctx) error
	// google oauth callback
	// (GET /api/auth/google/callback)
	GoogleCallback(c *fiber.Ctx, params GoogleCallbackParams) error
	// health check
	// (GET /api/auth/health)
	Health(c *fiber.Ctx) error
	// refresh tokens
	// (POST /api/auth/refresh)
	Refresh(c *fiber.Ctx) error
	// create channel
	// (POST /api/channels)
	CreateChannel(c *fiber.Ctx) error
	// delete channel
	// (DELETE /api/channels/{id})
	DeleteChannel(c *fiber.Ctx, id string) error
	// get channel by id
	// (GET /api/channels/{id})
	GetChannelByID(c *fiber.Ctx, id string) error
	// update channel
	// (PATCH /api/channels/{id})
	UpdateChannel(c *fiber.Ctx, id string) error
	// create space member
	// (POST /api/space-members)
	CreateSpaceMember(c *fiber.Ctx) error
	// delete space member
	// (DELETE /api/space-members/{id})
	DeleteSpaceMember(c *fiber.Ctx, id string) error
	// list spaces
	// (GET /api/spaces)
	ListSpaces(c *fiber.Ctx) error
	// create space
	// (POST /api/spaces)
	CreateSpace(c *fiber.Ctx) error
	// get space by id
	// (GET /api/spaces/{id})
	GetSpaceByID(c *fiber.Ctx, id string) error
	// delete space
	// (DELETE /api/spaces/{id}/channels)
	DeleteSpace(c *fiber.Ctx, id string) error
	// list channels by space id
	// (GET /api/spaces/{id}/channels)
	ListChannelsBySpace(c *fiber.Ctx, id string) error
	// update space
	// (PATCH /api/spaces/{id}/channels)
	UpdateSpace(c *fiber.Ctx, id string) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GithubLogin operation middleware
func (siw *ServerInterfaceWrapper) GithubLogin(c *fiber.Ctx) error {

	return siw.Handler.GithubLogin(c)
}

// GithubCallback operation middleware
func (siw *ServerInterfaceWrapper) GithubCallback(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GithubCallbackParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "code" -------------

	if paramValue := c.Query("code"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument code is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "code", query, &params.Code)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter code: %w", err).Error())
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := c.Query("state"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument state is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "state", query, &params.State)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter state: %w", err).Error())
	}

	return siw.Handler.GithubCallback(c, params)
}

// GoogleLogin operation middleware
func (siw *ServerInterfaceWrapper) GoogleLogin(c *fiber.Ctx) error {

	return siw.Handler.GoogleLogin(c)
}

// GoogleCallback operation middleware
func (siw *ServerInterfaceWrapper) GoogleCallback(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GoogleCallbackParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "code" -------------

	if paramValue := c.Query("code"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument code is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "code", query, &params.Code)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter code: %w", err).Error())
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := c.Query("state"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument state is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "state", query, &params.State)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter state: %w", err).Error())
	}

	return siw.Handler.GoogleCallback(c, params)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.Health(c)
}

// Refresh operation middleware
func (siw *ServerInterfaceWrapper) Refresh(c *fiber.Ctx) error {

	return siw.Handler.Refresh(c)
}

// CreateChannel operation middleware
func (siw *ServerInterfaceWrapper) CreateChannel(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.CreateChannel(c)
}

// DeleteChannel operation middleware
func (siw *ServerInterfaceWrapper) DeleteChannel(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.DeleteChannel(c, id)
}

// GetChannelByID operation middleware
func (siw *ServerInterfaceWrapper) GetChannelByID(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.GetChannelByID(c, id)
}

// UpdateChannel operation middleware
func (siw *ServerInterfaceWrapper) UpdateChannel(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.UpdateChannel(c, id)
}

// CreateSpaceMember operation middleware
func (siw *ServerInterfaceWrapper) CreateSpaceMember(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.CreateSpaceMember(c)
}

// DeleteSpaceMember operation middleware
func (siw *ServerInterfaceWrapper) DeleteSpaceMember(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.DeleteSpaceMember(c, id)
}

// ListSpaces operation middleware
func (siw *ServerInterfaceWrapper) ListSpaces(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.ListSpaces(c)
}

// CreateSpace operation middleware
func (siw *ServerInterfaceWrapper) CreateSpace(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.CreateSpace(c)
}

// GetSpaceByID operation middleware
func (siw *ServerInterfaceWrapper) GetSpaceByID(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.GetSpaceByID(c, id)
}

// DeleteSpace operation middleware
func (siw *ServerInterfaceWrapper) DeleteSpace(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.DeleteSpace(c, id)
}

// ListChannelsBySpace operation middleware
func (siw *ServerInterfaceWrapper) ListChannelsBySpace(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.ListChannelsBySpace(c, id)
}

// UpdateSpace operation middleware
func (siw *ServerInterfaceWrapper) UpdateSpace(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.UpdateSpace(c, id)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/api/auth/github", wrapper.GithubLogin)

	router.Get(options.BaseURL+"/api/auth/github/callback", wrapper.GithubCallback)

	router.Get(options.BaseURL+"/api/auth/google", wrapper.GoogleLogin)

	router.Get(options.BaseURL+"/api/auth/google/callback", wrapper.GoogleCallback)

	router.Get(options.BaseURL+"/api/auth/health", wrapper.Health)

	router.Post(options.BaseURL+"/api/auth/refresh", wrapper.Refresh)

	router.Post(options.BaseURL+"/api/channels", wrapper.CreateChannel)

	router.Delete(options.BaseURL+"/api/channels/:id", wrapper.DeleteChannel)

	router.Get(options.BaseURL+"/api/channels/:id", wrapper.GetChannelByID)

	router.Patch(options.BaseURL+"/api/channels/:id", wrapper.UpdateChannel)

	router.Post(options.BaseURL+"/api/space-members", wrapper.CreateSpaceMember)

	router.Delete(options.BaseURL+"/api/space-members/:id", wrapper.DeleteSpaceMember)

	router.Get(options.BaseURL+"/api/spaces", wrapper.ListSpaces)

	router.Post(options.BaseURL+"/api/spaces", wrapper.CreateSpace)

	router.Get(options.BaseURL+"/api/spaces/:id", wrapper.GetSpaceByID)

	router.Delete(options.BaseURL+"/api/spaces/:id/channels", wrapper.DeleteSpace)

	router.Get(options.BaseURL+"/api/spaces/:id/channels", wrapper.ListChannelsBySpace)

	router.Patch(options.BaseURL+"/api/spaces/:id/channels", wrapper.UpdateSpace)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZW3PbNhP9Kxh83yNjKbXbzujNdtrEk+v48tKMxwORKxExCdDA0rXi0X/vACAtkiJp",
	"SpaUquGbROKyl3N2D8BH6ss4kQIEajp6pNoPIWb252nIhIDI/GRBwJFLwaIvSiagkIOmowmLNHg0KTx6",
	"pCzFUKobHpg/OEuAjqhGxcWUzj3quzVv3ItHCiKN6egrRXhA6tF7yX2g117NRAUMIbhhaKZNpIrNLxow",
	"hFfIY6A1cxpsECyG2hc6YT40WZ4mwYoGzD2q4C7lCgLjIg+oV4hOYbvMpEp0Sj4vQiLH38BHY1GWn0t5",
	"asetmKe1M7FO+CqheMbzVmevbB5WdLbB5opZdlTd5n8oJdVHljTvWhOOpVXOgnPQiRTamlI2sEvUeFBr",
	"3DlMFOjwHO5S0Li8tHLvb1DegqjfZWnNC5OgzRJ/B/zdPEVzdLYT0UbrI8RjUGuSsb3yaFCr0iqf02ju",
	"moa+kEjZ1j+CwxfIMNVFBq7P5EtDpWYyM98HrRsJ51F4SLgCfcNFCahc4G9HC5BygTAFRa2H7Rz2qH3z",
	"VMxrMWRe/F/BhI7o/waLrj/IWv7gyoypLQdX2exV2ssafIeY8ag03D3pXhqMm804qfhlWhb4qeI4uzAh",
	"cIYfJ/w9zI5TDG1dFnREQ2ABqLwcjOixrRD8OzOxWFjH7Ew6NwtzMZFmfgDaVzyxA0f0L1D8O4SMjJl/",
	"CyIgx1/OzHyOERRfu8f3oLSb9/pgaLyTCQiWcDqihwfDg0Pq0YRhaK0esIQPTOUaTDmG6dg8mwIum6Ag",
	"4Ap81AQlecvxXTomn623dn1lfToL6Ii+tQt9kFNufFQZ2u1uh8Pfl1e+hDiRiqkZOc/2cCFO45ipmc0E",
	"U0icfUQytyeyqTa8tSZcmwlVVwY+iyITsEaf4MHIhylo4ssAPKIAUyWMh7cgdINjp/mqJoqKxYCgjCVZ",
	"zu9SULNFys3CtFhpUKXgZWq5Fm3162g0hW+Vha4rsf9lOLT8kgJB2GCwJIm4b/0bfNNSLGT8c4wv1zEL",
	"3HJkP783uDva4JZPUqpmtxMWkFzGzD366462PRNoqkZELkDdgyJ2bAW7RdQSfwGdVvhKOY2gIxPt2CYm",
	"2pebZ6LbsxMT7dDNM9Eu2zOxZ+IKTCygtisTQ2CR6+e1qHWviR+CXamM0Xdu7hZzX1GmDckvqBXLjaJO",
	"+XptwLmIUcWhttBkytKKWKlbKZ0NdWQmE6mIgL+zfwnjail02ck0IxloPJHBbGNhq5x75+WTgCHz/Kcl",
	"7NHw9U62vRIs08IQ/NsKRQmuupkG2dWTLlKgjGN3Us6vQ7eD5upl3o7hXLib6pvPEqa61l136CX+E1Jy",
	"yJ3mGFuG3eCRB3NXdiNwlyJl9L2xzxfoq9NI5hy4kDb2BugluuZouQ18kuQ0y4CFwtFOcvJJIvlTpiLY",
	"MyC4XLYDwcvFSEUTA2aDTmZnb3aT7+Gmy1hbEemR04acKWAOGzKeEZvaWvAkDP1wGT7uanXb1WKL/S+7",
	"G+7U/zrUqR8kv3qQt4Hcfajp1iftR41Xsf268qxGK3yJ2ZJOq/vW02u1/dVqFl4kziGTA9GmuRGGHTVb",
	"GY29btsb3bYSKHThXqmMgg9cYzbnheWAI8S6U2kqfK9kSrFZc4nYo7REXCPReSSX0uE93xO22Q36PvBf",
	"6QPPc/2p8jed3ey8fTy5ZdWjP7etf25zbaN6amtDUunysYOY6GXE3smI+obVqBfyE9DJbIcJ34IYeboI",
	"6ipHekx10EB5uTBFxlWbNS+ItguurQmt/nLop7kcahZkdjGzusNsqiI6ogM6v57/EwAA//8KXLR+zTAA",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
