// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for ChannelChannelType.
const (
	ChannelChannelTypeText  ChannelChannelType = "text"
	ChannelChannelTypeVoice ChannelChannelType = "voice"
)

// Defines values for ChannelToCreateChannelType.
const (
	ChannelToCreateChannelTypeText  ChannelToCreateChannelType = "text"
	ChannelToCreateChannelTypeVoice ChannelToCreateChannelType = "voice"
)

// AdminUserToUpdate defines model for AdminUserToUpdate.
type AdminUserToUpdate struct {
	Confirmed bool `json:"confirmed"`
}

// AdminUsersPage defines model for AdminUsersPage.
type AdminUsersPage struct {
	Items      []User  `json:"items"`
	NextCursor *string `json:"next_cursor,omitempty"`
}

// Channel defines model for Channel.
type Channel struct {
	AuthorId    string             `json:"author_id"`
	ChannelType ChannelChannelType `json:"channel_type"`
	CreatedAt   time.Time          `json:"created_at"`
	Id          string             `json:"id"`
	Name        string             `json:"name"`
	SpaceId     string             `json:"space_id"`
	UpdatedAt   *time.Time         `json:"updated_at,omitempty"`
}

// ChannelChannelType defines model for Channel.ChannelType.
type ChannelChannelType string

// ChannelToCreate defines model for ChannelToCreate.
type ChannelToCreate struct {
	ChannelType ChannelToCreateChannelType `json:"channel_type"`
	Name        string                     `json:"name"`
	SpaceId     string                     `json:"space_id"`
}

// ChannelToCreateChannelType defines model for ChannelToCreate.ChannelType.
type ChannelToCreateChannelType string

// ChannelToUpdate defines model for ChannelToUpdate.
type ChannelToUpdate struct {
	Name string `json:"name"`
}

// ErrorMap defines model for ErrorMap.
type ErrorMap map[string]string

// IdResponse defines model for IdResponse.
type IdResponse struct {
	Id string `json:"id"`
}

// MeToUpdate defines model for MeToUpdate.
type MeToUpdate struct {
	Username string `json:"username"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// Space defines model for Space.
type Space struct {
	AuthorId  string     `json:"author_id"`
	CreatedAt time.Time  `json:"created_at"`
	Id        string     `json:"id"`
	Name      string     `json:"name"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// SpaceMemberToCreate defines model for SpaceMemberToCreate.
type SpaceMemberToCreate struct {
	SpaceId string `json:"space_id"`
	UserId  string `json:"user_id"`
}

// SpaceMemberView defines model for SpaceMemberView.
type SpaceMemberView struct {
	AvatarUrl     *string              `json:"avatar_url"`
	CreatedAt     time.Time            `json:"created_at"`
	Email         *openapi_types.Email `json:"email,omitempty"`
	IsAdmin       bool                 `json:"is_admin"`
	SpaceId       string               `json:"space_id"`
	SpaceMemberId string               `json:"space_member_id"`
	UserId        string               `json:"user_id"`
	Username      string               `json:"username"`
}

// SpaceToCreate defines model for SpaceToCreate.
type SpaceToCreate struct {
	Name string `json:"name"`
}

// SpaceToUpdate defines model for SpaceToUpdate.
type SpaceToUpdate struct {
	Name string `json:"name"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse map[string]string

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken  *string `json:"access_token,omitempty"`
	ExpiresIn    *int64  `json:"expires_in,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
	TokenType    *string `json:"token_type,omitempty"`
	User         *User   `json:"user,omitempty"`
}

// User defines model for User.
type User struct {
	Confirmed   *bool                `json:"confirmed,omitempty"`
	ConfirmedAt *time.Time           `json:"confirmed_at,omitempty"`
	ConfirmedBy *string              `json:"confirmed_by"`
	CreatedAt   *time.Time           `json:"created_at,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	Id          *string              `json:"id,omitempty"`
	IsAdmin     *bool                `json:"is_admin,omitempty"`
	Username    *string              `json:"username,omitempty"`
}

// UserSearchPage defines model for UserSearchPage.
type UserSearchPage struct {
	Items      []UserSearchResult `json:"items"`
	NextCursor *string            `json:"next_cursor,omitempty"`
}

// UserSearchResult defines model for UserSearchResult.
type UserSearchResult struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	Id       string               `json:"id"`
	IsAdmin  bool                 `json:"is_admin"`
	Username string               `json:"username"`
}

// VoiceMember defines model for VoiceMember.
type VoiceMember struct {
	AvatarUrl *string `json:"avatar_url"`
	Deafened  bool    `json:"deafened"`
	Id        string  `json:"id"`
	IsAdmin   bool    `json:"is_admin"`
	Muted     bool    `json:"muted"`
	Username  string  `json:"username"`
}

// VoiceStateUpdate defines model for VoiceStateUpdate.
type VoiceStateUpdate struct {
	Deafened bool `json:"deafened"`
	Muted    bool `json:"muted"`
}

// WebRTCBootstrapResponse defines model for WebRTCBootstrapResponse.
type WebRTCBootstrapResponse struct {
	ConnectionId string            `json:"connection_id"`
	Publishers   []WebRTCPublisher `json:"publishers"`
	RoomId       string            `json:"room_id"`
	SelfFeedId   string            `json:"self_feed_id"`
}

// WebRTCPublisher defines model for WebRTCPublisher.
type WebRTCPublisher struct {
	Display *string `json:"display"`
	FeedId  string  `json:"feed_id"`
}

// ListAdminUsersParams defines parameters for ListAdminUsers.
type ListAdminUsersParams struct {
	Query     *string `form:"query,omitempty" json:"query,omitempty"`
	Limit     *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor    *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Confirmed *bool   `form:"confirmed,omitempty" json:"confirmed,omitempty"`
}

// GithubCallbackParams defines parameters for GithubCallback.
type GithubCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// GoogleCallbackParams defines parameters for GoogleCallback.
type GoogleCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// YandexCallbackParams defines parameters for YandexCallback.
type YandexCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// SearchUsersParams defines parameters for SearchUsers.
type SearchUsersParams struct {
	Query  *string `form:"query,omitempty" json:"query,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// UpdateAdminUserJSONRequestBody defines body for UpdateAdminUser for application/json ContentType.
type UpdateAdminUserJSONRequestBody = AdminUserToUpdate

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// CreateChannelJSONRequestBody defines body for CreateChannel for application/json ContentType.
type CreateChannelJSONRequestBody = ChannelToCreate

// UpdateChannelJSONRequestBody defines body for UpdateChannel for application/json ContentType.
type UpdateChannelJSONRequestBody = ChannelToUpdate

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = MeToUpdate

// CreateSpaceMemberJSONRequestBody defines body for CreateSpaceMember for application/json ContentType.
type CreateSpaceMemberJSONRequestBody = SpaceMemberToCreate

// CreateSpaceJSONRequestBody defines body for CreateSpace for application/json ContentType.
type CreateSpaceJSONRequestBody = SpaceToCreate

// UpdateSpaceJSONRequestBody defines body for UpdateSpace for application/json ContentType.
type UpdateSpaceJSONRequestBody = SpaceToUpdate

// UpdateVoiceStateJSONRequestBody defines body for UpdateVoiceState for application/json ContentType.
type UpdateVoiceStateJSONRequestBody = VoiceStateUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// list users (admin only)
	// (GET /api/admin/users)
	ListAdminUsers(c *fiber.Ctx, params ListAdminUsersParams) error
	// update user (admin only)
	// (PATCH /api/admin/users/{id})
	UpdateAdminUser(c *fiber.Ctx, id string) error
	// start github oauth
	// (GET /api/auth/github)
	GithubLogin(c *fiber.Ctx) error
	// github oauth callback
	// (GET /api/auth/github/callback)
	GithubCallback(c *fiber.Ctx, params GithubCallbackParams) error
	// start google oauth
	// (GET /api/auth/google)
	GoogleLogin(c *fiber.Ctx) error
	// google oauth callback
	// (GET /api/auth/google/callback)
	GoogleCallback(c *fiber.Ctx, params GoogleCallbackParams) error
	// health check
	// (GET /api/auth/health)
	Health(c *fiber.Ctx) error
	// logout
	// (POST /api/auth/logout)
	Logout(c *fiber.Ctx) error
	// refresh tokens
	// (POST /api/auth/refresh)
	Refresh(c *fiber.Ctx) error
	// start yandex oauth
	// (GET /api/auth/yandex)
	YandexLogin(c *fiber.Ctx) error
	// yandex oauth callback
	// (GET /api/auth/yandex/callback)
	YandexCallback(c *fiber.Ctx, params YandexCallbackParams) error
	// create channel
	// (POST /api/channels)
	CreateChannel(c *fiber.Ctx) error
	// bootstrap janus webrtc signaling for voice channel
	// (POST /api/channels/voice/{id}/webrtc/bootstrap)
	VoiceWebRTCBootstrap(c *fiber.Ctx, id string) error
	// delete channel
	// (DELETE /api/channels/{id})
	DeleteChannel(c *fiber.Ctx, id string) error
	// get channel by id
	// (GET /api/channels/{id})
	GetChannelByID(c *fiber.Ctx, id string) error
	// update channel
	// (PATCH /api/channels/{id})
	UpdateChannel(c *fiber.Ctx, id string) error
	// get current user
	// (GET /api/me)
	GetMe(c *fiber.Ctx) error
	// update current user
	// (PATCH /api/me)
	UpdateMe(c *fiber.Ctx) error
	// create space member
	// (POST /api/space-members)
	CreateSpaceMember(c *fiber.Ctx) error
	// delete space member
	// (DELETE /api/space-members/{id})
	DeleteSpaceMember(c *fiber.Ctx, id string) error
	// list spaces
	// (GET /api/spaces)
	ListSpaces(c *fiber.Ctx) error
	// create space
	// (POST /api/spaces)
	CreateSpace(c *fiber.Ctx) error
	// get space by id
	// (GET /api/spaces/{id})
	GetSpaceByID(c *fiber.Ctx, id string) error
	// delete space
	// (DELETE /api/spaces/{id}/channels)
	DeleteSpace(c *fiber.Ctx, id string) error
	// list channels by space id
	// (GET /api/spaces/{id}/channels)
	ListChannelsBySpace(c *fiber.Ctx, id string) error
	// update space
	// (PATCH /api/spaces/{id}/channels)
	UpdateSpace(c *fiber.Ctx, id string) error
	// list space members (owner only)
	// (GET /api/spaces/{id}/members)
	ListSpaceMembers(c *fiber.Ctx, id string) error
	// remove user from space (owner only)
	// (DELETE /api/spaces/{spaceId}/members/{userId})
	RemoveSpaceMember(c *fiber.Ctx, spaceId string, userId string) error
	// search confirmed users
	// (GET /api/users/search)
	SearchUsers(c *fiber.Ctx, params SearchUsersParams) error
	// join voice channel (presence)
	// (POST /api/voice/channels/{id}/join)
	JoinVoiceChannel(c *fiber.Ctx, id string) error
	// list voice members (presence)
	// (GET /api/voice/channels/{id}/members)
	ListVoiceMembers(c *fiber.Ctx, id string) error
	// voice presence heartbeat
	// (POST /api/voice/heartbeat)
	VoiceHeartbeat(c *fiber.Ctx) error
	// leave active voice channel (presence)
	// (POST /api/voice/leave)
	LeaveVoice(c *fiber.Ctx) error
	// update voice state (muted/deafened)
	// (POST /api/voice/state)
	UpdateVoiceState(c *fiber.Ctx) error
	// voice presence websocket
	// (GET /api/ws/voice/{spaceId})
	VoicePresenceWebSocket(c *fiber.Ctx, spaceId string) error
	// webrtc signaling websocket
	// (GET /api/ws/webrtc/{connectionId})
	WebRTCWebSocket(c *fiber.Ctx, connectionId string) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// ListAdminUsers operation middleware
func (siw *ServerInterfaceWrapper) ListAdminUsers(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAdminUsersParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, false, "query", query, &params.Query)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter query: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", query, &params.Cursor)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cursor: %w", err).Error())
	}

	// ------------- Optional query parameter "confirmed" -------------

	err = runtime.BindQueryParameter("form", true, false, "confirmed", query, &params.Confirmed)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter confirmed: %w", err).Error())
	}

	return siw.Handler.ListAdminUsers(c, params)
}

// UpdateAdminUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateAdminUser(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.UpdateAdminUser(c, id)
}

// GithubLogin operation middleware
func (siw *ServerInterfaceWrapper) GithubLogin(c *fiber.Ctx) error {

	return siw.Handler.GithubLogin(c)
}

// GithubCallback operation middleware
func (siw *ServerInterfaceWrapper) GithubCallback(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GithubCallbackParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "code" -------------

	if paramValue := c.Query("code"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument code is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "code", query, &params.Code)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter code: %w", err).Error())
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := c.Query("state"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument state is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "state", query, &params.State)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter state: %w", err).Error())
	}

	return siw.Handler.GithubCallback(c, params)
}

// GoogleLogin operation middleware
func (siw *ServerInterfaceWrapper) GoogleLogin(c *fiber.Ctx) error {

	return siw.Handler.GoogleLogin(c)
}

// GoogleCallback operation middleware
func (siw *ServerInterfaceWrapper) GoogleCallback(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GoogleCallbackParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "code" -------------

	if paramValue := c.Query("code"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument code is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "code", query, &params.Code)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter code: %w", err).Error())
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := c.Query("state"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument state is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "state", query, &params.State)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter state: %w", err).Error())
	}

	return siw.Handler.GoogleCallback(c, params)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.Health(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *fiber.Ctx) error {

	return siw.Handler.Logout(c)
}

// Refresh operation middleware
func (siw *ServerInterfaceWrapper) Refresh(c *fiber.Ctx) error {

	return siw.Handler.Refresh(c)
}

// YandexLogin operation middleware
func (siw *ServerInterfaceWrapper) YandexLogin(c *fiber.Ctx) error {

	return siw.Handler.YandexLogin(c)
}

// YandexCallback operation middleware
func (siw *ServerInterfaceWrapper) YandexCallback(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params YandexCallbackParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "code" -------------

	if paramValue := c.Query("code"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument code is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "code", query, &params.Code)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter code: %w", err).Error())
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := c.Query("state"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument state is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "state", query, &params.State)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter state: %w", err).Error())
	}

	return siw.Handler.YandexCallback(c, params)
}

// CreateChannel operation middleware
func (siw *ServerInterfaceWrapper) CreateChannel(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.CreateChannel(c)
}

// VoiceWebRTCBootstrap operation middleware
func (siw *ServerInterfaceWrapper) VoiceWebRTCBootstrap(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.VoiceWebRTCBootstrap(c, id)
}

// DeleteChannel operation middleware
func (siw *ServerInterfaceWrapper) DeleteChannel(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.DeleteChannel(c, id)
}

// GetChannelByID operation middleware
func (siw *ServerInterfaceWrapper) GetChannelByID(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.GetChannelByID(c, id)
}

// UpdateChannel operation middleware
func (siw *ServerInterfaceWrapper) UpdateChannel(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.UpdateChannel(c, id)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.GetMe(c)
}

// UpdateMe operation middleware
func (siw *ServerInterfaceWrapper) UpdateMe(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.UpdateMe(c)
}

// CreateSpaceMember operation middleware
func (siw *ServerInterfaceWrapper) CreateSpaceMember(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.CreateSpaceMember(c)
}

// DeleteSpaceMember operation middleware
func (siw *ServerInterfaceWrapper) DeleteSpaceMember(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.DeleteSpaceMember(c, id)
}

// ListSpaces operation middleware
func (siw *ServerInterfaceWrapper) ListSpaces(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.ListSpaces(c)
}

// CreateSpace operation middleware
func (siw *ServerInterfaceWrapper) CreateSpace(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.CreateSpace(c)
}

// GetSpaceByID operation middleware
func (siw *ServerInterfaceWrapper) GetSpaceByID(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.GetSpaceByID(c, id)
}

// DeleteSpace operation middleware
func (siw *ServerInterfaceWrapper) DeleteSpace(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.DeleteSpace(c, id)
}

// ListChannelsBySpace operation middleware
func (siw *ServerInterfaceWrapper) ListChannelsBySpace(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.ListChannelsBySpace(c, id)
}

// UpdateSpace operation middleware
func (siw *ServerInterfaceWrapper) UpdateSpace(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.UpdateSpace(c, id)
}

// ListSpaceMembers operation middleware
func (siw *ServerInterfaceWrapper) ListSpaceMembers(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.ListSpaceMembers(c, id)
}

// RemoveSpaceMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveSpaceMember(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "spaceId" -------------
	var spaceId string

	err = runtime.BindStyledParameterWithOptions("simple", "spaceId", c.Params("spaceId"), &spaceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter spaceId: %w", err).Error())
	}

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Params("userId"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.RemoveSpaceMember(c, spaceId, userId)
}

// SearchUsers operation middleware
func (siw *ServerInterfaceWrapper) SearchUsers(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchUsersParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, false, "query", query, &params.Query)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter query: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", query, &params.Cursor)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cursor: %w", err).Error())
	}

	return siw.Handler.SearchUsers(c, params)
}

// JoinVoiceChannel operation middleware
func (siw *ServerInterfaceWrapper) JoinVoiceChannel(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.JoinVoiceChannel(c, id)
}

// ListVoiceMembers operation middleware
func (siw *ServerInterfaceWrapper) ListVoiceMembers(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.ListVoiceMembers(c, id)
}

// VoiceHeartbeat operation middleware
func (siw *ServerInterfaceWrapper) VoiceHeartbeat(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.VoiceHeartbeat(c)
}

// LeaveVoice operation middleware
func (siw *ServerInterfaceWrapper) LeaveVoice(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.LeaveVoice(c)
}

// UpdateVoiceState operation middleware
func (siw *ServerInterfaceWrapper) UpdateVoiceState(c *fiber.Ctx) error {

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.UpdateVoiceState(c)
}

// VoicePresenceWebSocket operation middleware
func (siw *ServerInterfaceWrapper) VoicePresenceWebSocket(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "spaceId" -------------
	var spaceId string

	err = runtime.BindStyledParameterWithOptions("simple", "spaceId", c.Params("spaceId"), &spaceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter spaceId: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.VoicePresenceWebSocket(c, spaceId)
}

// WebRTCWebSocket operation middleware
func (siw *ServerInterfaceWrapper) WebRTCWebSocket(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "connectionId" -------------
	var connectionId string

	err = runtime.BindStyledParameterWithOptions("simple", "connectionId", c.Params("connectionId"), &connectionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter connectionId: %w", err).Error())
	}

	c.Context().SetUserValue(ApiKeyAuthScopes, []string{})

	return siw.Handler.WebRTCWebSocket(c, connectionId)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/api/admin/users", wrapper.ListAdminUsers)

	router.Patch(options.BaseURL+"/api/admin/users/:id", wrapper.UpdateAdminUser)

	router.Get(options.BaseURL+"/api/auth/github", wrapper.GithubLogin)

	router.Get(options.BaseURL+"/api/auth/github/callback", wrapper.GithubCallback)

	router.Get(options.BaseURL+"/api/auth/google", wrapper.GoogleLogin)

	router.Get(options.BaseURL+"/api/auth/google/callback", wrapper.GoogleCallback)

	router.Get(options.BaseURL+"/api/auth/health", wrapper.Health)

	router.Post(options.BaseURL+"/api/auth/logout", wrapper.Logout)

	router.Post(options.BaseURL+"/api/auth/refresh", wrapper.Refresh)

	router.Get(options.BaseURL+"/api/auth/yandex", wrapper.YandexLogin)

	router.Get(options.BaseURL+"/api/auth/yandex/callback", wrapper.YandexCallback)

	router.Post(options.BaseURL+"/api/channels", wrapper.CreateChannel)

	router.Post(options.BaseURL+"/api/channels/voice/:id/webrtc/bootstrap", wrapper.VoiceWebRTCBootstrap)

	router.Delete(options.BaseURL+"/api/channels/:id", wrapper.DeleteChannel)

	router.Get(options.BaseURL+"/api/channels/:id", wrapper.GetChannelByID)

	router.Patch(options.BaseURL+"/api/channels/:id", wrapper.UpdateChannel)

	router.Get(options.BaseURL+"/api/me", wrapper.GetMe)

	router.Patch(options.BaseURL+"/api/me", wrapper.UpdateMe)

	router.Post(options.BaseURL+"/api/space-members", wrapper.CreateSpaceMember)

	router.Delete(options.BaseURL+"/api/space-members/:id", wrapper.DeleteSpaceMember)

	router.Get(options.BaseURL+"/api/spaces", wrapper.ListSpaces)

	router.Post(options.BaseURL+"/api/spaces", wrapper.CreateSpace)

	router.Get(options.BaseURL+"/api/spaces/:id", wrapper.GetSpaceByID)

	router.Delete(options.BaseURL+"/api/spaces/:id/channels", wrapper.DeleteSpace)

	router.Get(options.BaseURL+"/api/spaces/:id/channels", wrapper.ListChannelsBySpace)

	router.Patch(options.BaseURL+"/api/spaces/:id/channels", wrapper.UpdateSpace)

	router.Get(options.BaseURL+"/api/spaces/:id/members", wrapper.ListSpaceMembers)

	router.Delete(options.BaseURL+"/api/spaces/:spaceId/members/:userId", wrapper.RemoveSpaceMember)

	router.Get(options.BaseURL+"/api/users/search", wrapper.SearchUsers)

	router.Post(options.BaseURL+"/api/voice/channels/:id/join", wrapper.JoinVoiceChannel)

	router.Get(options.BaseURL+"/api/voice/channels/:id/members", wrapper.ListVoiceMembers)

	router.Post(options.BaseURL+"/api/voice/heartbeat", wrapper.VoiceHeartbeat)

	router.Post(options.BaseURL+"/api/voice/leave", wrapper.LeaveVoice)

	router.Post(options.BaseURL+"/api/voice/state", wrapper.UpdateVoiceState)

	router.Get(options.BaseURL+"/api/ws/voice/:spaceId", wrapper.VoicePresenceWebSocket)

	router.Get(options.BaseURL+"/api/ws/webrtc/:connectionId", wrapper.WebRTCWebSocket)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc61PcOBL/V1S++8DWzcbkkr2rmm/A3ibshl0KSLbuUhSlsXvGCrbkSDIwS/G/X0ny",
	"+zW2MwYm+FPCWI9u6ffrbrUe95bDgpBRoFJY83tLOB4EWP/3wA0I/SiAX7CPoYslqB+x6xJJGMX+KWch",
	"cElAWPMl9gXMrDD3k2qYLgkPwFV/yHUI1txaMOYDptbDw8zi8DUiXH3+nCt7OUvKssUXcKT1MMskEad4",
	"1VcMIiEo/ufvHJbW3Pqbnalux3rbqhfVZSwD5hyv1d8U7uSVE3HBeE4dITmhq4o2pqc6TY48TCn4PVXA",
	"kfQYvyJuTdczyzFtXpkP9xbQKFBSSLiT1sy6YcSBnDC5ihywBPcKS1VtyXig/mepqf5RkgCsmjoNMlAc",
	"QO0HEWIHmiSPNKz6CFAeaNea5UYn110sUml0Cjq3zM8FO9Ll+iJ+6EwMGb7SUGzQvFXZQfRukLkkli5V",
	"1/l/OGf8BIfNvdYMR6WVY/cMRMio0KKUiN9h1Ei9wTmBgYMSCeDdBiYtWdf/GSw5CO8MvkYgZFU1br5f",
	"SXYNtL6vSpvnCiDbNTyPYD+2byISdrQbAj1aJxAslPsbZAzaLZ8A3pfWSZ0N4n4icNt3mm+wxPwq4tox",
	"0cj38cIHay55BFvyGxBg4heKm1/qICKusHL4dWHDBodiPgZ6HPoP/awHfcs9zepmKtdgTq1u2BuIum+0",
	"ynHXT+EQziWWkcib8+Fu4ULZxWbPgB0HhGi0njML7kLCQVwZEKaQJVT+620GWUIlrEy4uMkgzyz9JY0M",
	"apHXLTat0/djXHtb0fks+9yL5VmtxfpZmJJ6mrdbmHYjUDv254C54z3K4sR0dQYi8uWIC5VKV/30eto5",
	"qvj/OjNcp/UnFaEbNzquC3UBL4E2kW/QkASRbGpvC6OVtJ8TvXEAlSWHQS6kfVgaNSwp0UnSP2FxdnF0",
	"yJgUkuNws99psqIUHFW4KaQIo4VPhAe8O82NaKdJxTqWc8aCxiAI/OXVEsDtFGAWNchaLrVTUKR5PDOh",
	"e048EaGPu/mMzqolBavi6lFyIk7k+lwNuhHiICS/wfogkp6eKmrNLQ+wCzxZNcytA72QIH9hpVdmzbCu",
	"aT2ohgldMoNl4XAS6oJz63/AyV/gYbTAzjVQFx2cHqv6RCpNs8/m5xvgwtR7/Wpf6cxCoDgk1tx682r/",
	"1Rs1HVh6Wmobh8TWJLUVcfVvK9AGW42wlvTYtebWByJklknTTXAcgNR1PscKf42ArzN9kz8NNGuHvL6i",
	"TwIiCxUDfEeCKLDmP+3PrIBQ88frajTV1GTs1AYIk8U6NZUzK3Kp4GPMgB7Ff+7vxxyXQI0HDEOfOHpI",
	"7S+C0SxjuonTpRSmRkoRIX/8pib67f7rrfWZplhqevtIcQxlcE2/bx6l318YXxDXBW3Qf9riALd1ekyl",
	"8mg+Ogd+AxzpsgUroAmQ5//nSwUHEQUB5muNZyGR5hfa02RDjPrrHxSF8UrxxySprUvVapmS9j1xH/Qy",
	"BEvHqzLT+MoUIg3UVIzPMG2MdWrtjK1sZsalKQxCHjJ3vX1Yp2vGh6IVVnI9VHj1tmogf2foKJZIw/Fx",
	"kHGIXZRk2V4a+96aaRi909+ZRL+wiLo7RnmTetSk78z5SHr2ikgvWuTccFEyDi7h4EiBJEPviHwfLdAf",
	"WoJZySy80w19YCsdfxco9Gb/39WWLyAIGcd8jc7iPozCqUZCYi6RkQ8xbPpMdVF/1qpiO9j3VdzSqBPc",
	"OR6mKxDIYS7MEAcZcao0vAYqGhQ7SlrtFImohntZvIZYQKjFSX/TOVJYUExUtUQFT2IOnwFZU+zmUYuc",
	"DDqt8GVs5UNHJuqyTUzUH7fPRNNnJybqottnom52YuLExB5MzKG2KxM9wL5ZVtei1nxGjge6pSJG35u6",
	"I859aeuhYfL7xA4lhdqGxmcrFpk9XiZqxsbxAXOBzGgzdk2gSuMPpo2+cXZhWv2kjTZh432OZmkz+xMX",
	"NZYHLRlHFG7jv0JMeEWJeNPbGmelUtpS77RMeSnW5amWPc/JqhXgKjbQYI2pC3fdAov/6rINgYX5uPXA",
	"wsjXKbAwRbceWBjFpsBiCiy6UzCP2g6BRXy+TeSdURGE5gRFcuZyHL9SPjH4yI4ldwBugtbgVI85hoCc",
	"FCkJ5I4SjFVhZ+vjnDq1a9/CgkvHXiS7ic2Q1Bukpb3H0fK9I2Guaet0CmumbO6zpXjKTfQF00ggQ1kk",
	"yIpin9CVXqFoSteYgU/m5HbVBiQbOy74YE47FOn+s/4980CPwPMOeysTUtqQYuay3RnM6rfY34GMCx2u",
	"j3/eNbuewLTFjk/IaUPOCmQCG7RYIz21teBp3Qce21qMGAN/H3vAE8g7bIt2ipUDaDyN9A7kCYyZ1I1P",
	"Sz+zcza7Zs0izoGaky+5qTYnyDZashMYadGdu5/1yOvtTah6rNm9wT5xEZ9yuAMsVzumE9ul7/P8aG74",
	"bMwx5e5fjQT5ugtpU65pd3NNGl4oSCCToFBPcyMMO643i2ic1pw7s+bsBYr2k95xnW80B53uK5ibxZVb",
	"Ck0mYtdO/YpkJCvTMdvsE8b0BpMf+F78wGaup5a/aTGl6+1i1im2HlPOafgqzbiNcsapDUmFzdMOwcQU",
	"RuxcGFHvsBrjhSR7c7h+xAkfIRhJk9hdw5EJUx1ioMRcKCNjrM3A5Pa44Bot0JoS2y8msd0nILNz6aH2",
	"ldhJXHBXzWr5gaEe5nU6hDFRrLKejpMcAu2xWwq8crOukXX63+OMevZ9JIAft6fFziBgN73TYnFXg46k",
	"FlsyIo4fHU9Um6iWnmdXkDe3V5ecBTHtutLN3FsX+gWgRu9mHgj6fp+TuBx5IzH3bNS0UT0c6galKH3l",
	"w7zT0LK1Z07uFg7x2V+YeVipPqP7KyNUHwJ8bkf5poO1k6N5WvYp4hQPzqK9kIMA6sAPLWdo60jYZTmV",
	"e6Ntd5dT+YfmpqXURLuBSylDu3Qp1Z12HmAuF4Dlhpsq79Nyu7Mc2aFJNPOXTBvycqPdPn8+4BtonrsP",
	"6rOpOc3bGORT44uwI8kNDPd95p5q4ySanHP2ouZIRwkqT3ZOL3i9iGOQBrYag2hPP5lqJw+mtkH3Nr34",
	"mGTiGq+M/wmLc+Zcg0TSwxKFkfBAlHyWEUbo21c4yVFwCH3sgEhLhczXd7T+kZnIHypXzrWkpzH70r5H",
	"y/SV48TXBnnFITi/JdLxlOinnEnmMF+8OHJ8g0O8hYVIZrEFkPH12/vsLdtusIzCFccuIKBuyAiVGoW/",
	"6uuB2b3APbZcArcxFbfAbcmJc+1DFX3mUmw/2OXlnbD31Nir3AhtRZ9uWZlgM7v64W/Lth4uH/4fAAD/",
	"/07mNBBTawAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
